/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package rpn;

import java.util.ArrayDeque;
import java.util.Deque;
import java.util.NoSuchElementException;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        try (Scanner sc = new Scanner(System.in)) {
            Deque<Integer> stack = new ArrayDeque<Integer>();

            try {
                int result = Evaluator.evaluate(stack, Parser.parse(sc.nextLine()));
                System.out.println(result);
            } catch (Exception e) {
                System.out.println("An exception occurred: " + e.getMessage());
            }

        } catch (NoSuchElementException e) {
            System.out.println("The line could not be found");
        }
    }
}
